package de.savannahnixon.backend.app.dtos;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder
@NoArgsConstructor
public abstract class BaseDto {
  @Schema(description = "Autogenerated Uuid", nullable = false)
  @NotNull
  private String id;

  @Schema(description = "Creation date", nullable = false, format = "date-time")
  @NotNull
  private String createdAt;

  @Schema(description = "Last update date", nullable = false, format = "date-time")
  @NotNull
  private String updatedAt;
}
