package de.savannahnixon.backend.app.dtos;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

@Data
@SuperBuilder
@NoArgsConstructor
public abstract class BaseDto {
  @Schema(description = "Autogenerated Uuid", nullable = false, example = "123e4567-e89b-12d3-a456-426614174000")
  @NotNull
  private String id;

  @Schema(description = "Creation date", nullable = false, format = "date-time", example = "Sun Mar 03 16:38:25 CET 2024")
  @NotNull
  private String createdAt;

  @Schema(description = "Last update date", nullable = false, format = "date-time", example = "Sun Mar 03 16:38:25 CET 2024")
  @NotNull
  private String updatedAt;
}
